Implementation for React on Rails App
Bantealem/React_on_Rails pull request #1
Opened 2023-01-20 08:17 UTC by Bantealem

In this pull request, I have done the following
- [x] I have created a table 
- [x]  I have generated API

2023-01-20 10:51 UTC, elisha2kyakpo1 requested changes
Hi 👋 @Bantealem, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ The PR title and description look good and professional.
✔️ No linter errors.
✔️ Descriptive readme file.

## Required Changes ♻️
_Check the comments under the review._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 10:51 UTC, elisha2kyakpo1 commented on app/javascript/App.jsx
> +    );
- [ ] I did not see any greetings(messages) on the screen even after creating 5 messages. Kindly fix the issue.

![one-app](https://user-images.githubusercontent.com/53124548/213677899-34be94bb-1443-4c87-94e6-e2be338de361.png)

2023-01-20 10:51 UTC, elisha2kyakpo1 commented on README.md
> +  <img src="https://github.com/microverseinc/readme-template/raw/master/murple_logo.png" alt="logo" width="140"  height="auto" />
- [ ] Kindly remove the Microverse logo (replace it with the app logo if you have one)

2023-01-20 10:51 UTC, elisha2kyakpo1 commented on db/migrate/20230117113947_create_greetings.rb
> +
- [ ] One of this project requirements is that you should create a table for storing 5 messages, so in this case, you can use a seed file to create a function that will create those messages.

![messages](https://user-images.githubusercontent.com/53124548/213676224-11d444ab-f03c-490d-b61d-26247b2c96d3.png)

2023-01-28 17:02 UTC, BenMukebo requested changes
### Hi @

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- API endpoint for returning a random greeting was created. ✔️  
- Database table for storing different greetings was created. ✔️  
- The view for the root route is created. ✔️
- There is a `Greeting` component. ✔️
- The `App`component has a route that leads to the `Greeting` component.
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-28 17:02 UTC, BenMukebo commented on README.md
> +
- [ ] I would recommend adding the issue link in the contributing sections: 

```
## 🤝 Contributing

Contributions, issues, and feature requests are welcome!

Feel free to check the [issues page](../../issues/).
```

2023-01-28 17:02 UTC, BenMukebo commented on README.md
> +
- [ ] Please update your Readme, it will be nice to add and update this section(`License`) with the type of License and a link to the license file, as this will make your readme more informative and professional. 
- When I click the link to the `MIT.md` file that you added, I get this 404 `error`:

![00Mit](https://user-images.githubusercontent.com/79058364/182822618-fdfb2523-cb23-4060-9f72-75ec8c29e4cd.png)


#### The reason for this is that there is no `MIT.md` file in the root directory of this project. Kindly attach the file. 👍

2023-01-28 17:02 UTC, BenMukebo commented on README.md
> +### Run tests
- [ ] It will be nice to add explicit steps to clone and run your project locally, as this will be of help to non-technical users. You can put the steps to clone and run the project in a new Getting Started section under the project's description. This includes
- `git clone URL` , `cd project_name`,
- `bundle install`
- `rails db:create db:migrate db:seed`
- `yarn install`
- `yarn build`
- `./bin/dev`
etc 🙃  Please refer to this [template](https://github.com/microverseinc/readme-template), you can copy and paste the content but remember to customize it to your project.

- The README file It is the first file a person will see when they encounter your project, so it should be fairly brief but detailed. It will make your project stand out from a bunch of others.

2023-01-28 17:02 UTC, BenMukebo commented on app/javascript/redux/reducer.js
> +const getAllGreetings = (state) => state.greeting.greetings;
- [ ] Great job so far but there is some error that you need to fix.
- After run to app I'm seeing this 👇🏻 

![Screenshot from 2023-01-28 18-55-38](https://user-images.githubusercontent.com/79058364/215279108-59c84a19-b955-4616-b5d4-bd17cc64c98a.png)

- Based on the project requirement, the  React app should use the URL and displayes a random greeting however I'm getting this error instead when I reload the page  👇🏻  please fix this 
![Screenshot from 2023-01-28 18-55-59](https://user-images.githubusercontent.com/79058364/215279113-45fee769-b5cf-44e1-aa51-48d27d1972b0.png)

2023-01-28 19:24 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED 🍾✔🎉**
Hello @Bantealem 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- Your linters are passing all the checks.
- You asked for the changes in a polite and friendly way.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-29 10:37 UTC, merged